# Generated by Django 6.0.2 on 2026-02-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='countdown_seconds',
            field=models.IntegerField(default=59),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
