# Generated by Django 6.0.2 on 2026-02-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_herosection_countdown_seconds_herosection_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='event_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='event_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='event_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
