# Generated by Django 6.0.2 on 2026-02-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_herosection_event_date_herosection_event_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='countdown_days',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='countdown_hours',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='countdown_minutes',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='countdown_seconds',
        ),
        migrations.AddField(
            model_name='herosection',
            name='target_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
