# Generated by Django 6.0.2 on 2026-02-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_herosection_countdown_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title_gradient',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title_prefix',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='title',
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_ru',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_uz',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_uz',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='herosection',
            name='event_location_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='event_location_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_gradient_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_gradient_uz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_prefix_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_prefix_uz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_uz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='subtitle_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='subtitle_uz',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_uz',
            field=models.CharField(default='', max_length=200),
        ),
    ]
