# Generated by Django 6.0.2 on 2026-02-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_herosection_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='cta_link',
            field=models.URLField(default='https://bondolympiad.uz/register/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_text_ru',
            field=models.CharField(default='Купить билет', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_text_uz',
            field=models.CharField(default="Ro'yxatdan o'tish", max_length=100),
        ),
    ]
